[install]
# https://bun.sh/docs/runtime/bunfig#package-manager
exact = true
registry = { url = "https://registry.npmjs.org", token = "$NPM_TOKEN" }

[test]
# https://bun.sh/docs/runtime/bunfig#test-runner
coverage = true
coveragePathIgnorePatterns = "**/dist/**"
coverageThreshold = 0.7